# Mohamed Baher

In [1]:
#import our libraries
import numpy as np 
import pandas as pd

In [2]:
data = np.array([[1,2,3,4],
               [5,5,6,7],
               [1,4,2,3],
               [5,3,2,1],
               [8,1,2,2]])

# [1] standardization dataset

# $X = \frac{X - \mu}{\sigma}$      
# $\mu = \frac{\sum x_i}{n}$
# $\sigma = \sqrt{\frac{\sum (x - x_i)^2}{n-1}}$

In [3]:
#new_valuee = (old_value - mean ) / std
#find mean and standard deviation for each column
mean_features = data.mean(axis = 0)
std_features = data.std(axis = 0)
print("mean_features : " , mean_features)
print("std_features : " , std_features)

mean_features :  [4.  3.  3.  3.4]
std_features :  [2.68328157 1.41421356 1.54919334 2.05912603]


In [4]:
#selcet each feature alone to apply standardization
new_data = []
for i in range (len(data)):
    column = data[:,i:i+1]
    mean = column.mean()
    std = column.std()
    for element in column:
        values = ((element - mean) / std)
        for items in values:
            new_data.append(items)
new_data = np.array(new_data)
new_data

C:\Users\Nv\AppData\Local\Temp/ipykernel_22448/1773283720.py:5: RuntimeWarning: Mean of empty slice.
  mean = column.mean()
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:261: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:221: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


array([-1.11803399,  0.372678  , -1.11803399,  0.372678  ,  1.49071198,
       -0.70710678,  1.41421356,  0.70710678,  0.        , -1.41421356,
        0.        ,  1.93649167, -0.64549722, -0.64549722, -0.64549722,
        0.29138576,  1.74831455, -0.19425717, -1.16554303, -0.6799001 ])

In [5]:
#reshape array to size(5,4) accrding to rows
data = np.reshape(new_data , (5,4) , order='F')
data

array([[-1.11803399, -0.70710678,  0.        ,  0.29138576],
       [ 0.372678  ,  1.41421356,  1.93649167,  1.74831455],
       [-1.11803399,  0.70710678, -0.64549722, -0.19425717],
       [ 0.372678  ,  0.        , -0.64549722, -1.16554303],
       [ 1.49071198, -1.41421356, -0.64549722, -0.6799001 ]])

since we have standarized the dataset,so the mean for each feature is 0 and the standard diviation is 1.

# [2] covariance matrix

# $C = \frac{XX^T}{n-1}$
# $\sigma ^2 (variance) = \frac{\sum (x - x_i)^2}{n-1}$

In [6]:
df = pd.DataFrame(data )
df

0         1         2         3
0 -1.118034 -0.707107  0.000000  0.291386
1  0.372678  1.414214  1.936492  1.748315
2 -1.118034  0.707107 -0.645497 -0.194257
3  0.372678  0.000000 -0.645497 -1.165543
4  1.490712 -1.414214 -0.645497 -0.679900

In [7]:
x = df[0]
x

0   -1.118034
1    0.372678
2   -1.118034
3    0.372678
4    1.490712
Name: 0, dtype: float64

In [8]:
data

array([[-1.11803399, -0.70710678,  0.        ,  0.29138576],
       [ 0.372678  ,  1.41421356,  1.93649167,  1.74831455],
       [-1.11803399,  0.70710678, -0.64549722, -0.19425717],
       [ 0.372678  ,  0.        , -0.64549722, -1.16554303],
       [ 1.49071198, -1.41421356, -0.64549722, -0.6799001 ]])

In [9]:
mean = 0
#f1 = np.array([-1 , 0.33333,  -1 , 0.33333 , 1.33333])
#f2 = np.array([-0.6 , 1.26491 , 0.63246 , 0 , -1.26491])
#f3 = np.array([])
#function that apply covariance on 2 features
def cov(x,y):
    summision = 0
    n = len(x)
    for i in range(len(x)):
        summision = summision + ((x[i] - mean) * (y[i] - mean))
    corr = (1 / (n - 1)) * summision
    return corr

In [10]:
cov(f2,f1)

-0.3243425

In [11]:
#function that apply covariance on 2 features
def var(x,y):
    n = len(x)
    summision = 0
    for i in range(len(x)):
        summision = summision + pow((x[i] - mean),2)
    var = summision / (n - 1)
    return var

In [12]:
#apply covariance on each column with each other columns
f1 = []
f2 = []
f3 = []
f4 = []
for i in range(4):
    x = cov(data[:,:1] , data[:,i:i+1])
    for j in x:
        f1.append(j)
for i in range(4):
    x = cov(data[:,1:2] , data[:,i:i+1])
    for j in x:
        f2.append(j)
for i in range(4):
    x = cov(data[:,2:3] , data[:,i:i+1])
    for j in x:
        f3.append(j)
for i in range(4):
    x = cov(data[:,3:] , data[:,i:i+1])
    for j in x:
        f4.append(j)

In [13]:
f1 = pd.Series(f1)
f2 = pd.Series(f2)
f3 = pd.Series(f3)
f4 = pd.Series(f4)
covariance_matrix = pd.DataFrame({'f1':f1 , 'f2':f2 , 'f3':f3 , 'f4':f4})
covariance_matrix

f1        f2        f3        f4
0  1.250000 -0.395285  0.060141 -0.226236
1 -0.395285  1.250000  0.798762  0.772653
2  0.060141  0.798762  1.250000  1.175554
3 -0.226236  0.772653  1.175554  1.250000

#  [3] calculate eigen values and eigen vectors

In [14]:
np.linalg.eigvals(covariance_matrix)

array([3.14474155, 1.33161063, 0.4923588 , 0.03128901])

In [15]:
#find eigen_vector & eigen_values of covariance_matrix 
eigens = np.linalg.eigh(covariance_matrix)
eigens

(array([0.03128901, 0.4923588 , 1.33161063, 3.14474155]),
 array([[ 0.19616173,  0.30707099,  0.91705888, -0.16195986],
        [ 0.12061043,  0.81731886, -0.20692161,  0.52404813],
        [-0.72009851, -0.1882497 ,  0.3205394 ,  0.58589647],
        [ 0.65454704, -0.44973251,  0.11593512,  0.59654663]]))

# [4]Sort eigen values and eigen vectors 

In [16]:
eigen_values = np.array([3.14474155,1.33161063,0.4923588,0.03128901])

In [17]:
eigen_vectors = np.array([[-0.16195986 , 0.91705888 ],
                         [0.52404813 , -0.20692161],
                         [0.58589647 , 0.3205394],
                         [0.59654663 , 0.11593512]])
eigen_vectors

array([[-0.16195986,  0.91705888],
       [ 0.52404813, -0.20692161],
       [ 0.58589647,  0.3205394 ],
       [ 0.59654663,  0.11593512]])

# Finally , Transform original matrix

In [18]:
eigen_vectors

array([[-0.16195986,  0.91705888],
       [ 0.52404813, -0.20692161],
       [ 0.58589647,  0.3205394 ],
       [ 0.59654663,  0.11593512]])

In [19]:
data

array([[-1.11803399, -0.70710678,  0.        ,  0.29138576],
       [ 0.372678  ,  1.41421356,  1.93649167,  1.74831455],
       [-1.11803399,  0.70710678, -0.64549722, -0.19425717],
       [ 0.372678  ,  0.        , -0.64549722, -1.16554303],
       [ 1.49071198, -1.41421356, -0.64549722, -0.6799001 ]])

In [20]:
new_data = data.dot(eigen_vectors)
new_data

array([[-1.56561657e-02, -8.45205481e-01],
       [ 2.85829189e+00,  8.72549255e-01],
       [ 5.75566079e-02, -1.40104719e+00],
       [-1.13385419e+00, -2.66998767e-04],
       [-1.76633814e+00,  1.37397042e+00]])

In [21]:
np.round(new_data , 3)

array([[-0.016, -0.845],
       [ 2.858,  0.873],
       [ 0.058, -1.401],
       [-1.134, -0.   ],
       [-1.766,  1.374]])

So , We finally perform Principal Component Analysis on our dataset 